name: Budibase CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Non-secret environment variables
  APP_PORT: 4002
  WORKER_PORT: 4003
  MINIO_PORT: 4004
  COUCH_DB_PORT: 4005
  REDIS_PORT: 6379
  WATCHTOWER_PORT: 6161
  BUDIBASE_ENVIRONMENT: DEVELOPMENT

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate configuration files
        run: |
          [ -f docker-compose.yaml ] || { echo "Missing docker-compose.yaml"; exit 1; }
          [ -f .env ] || { echo "Missing .env file"; exit 1; }

  test:
    needs: validate
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up MinIO
        run: |
          docker run -d \
            --name minio \
            -p 9000:9000 \
            -p 9001:9001 \
            -e "MINIO_ACCESS_KEY=minio" \
            -e "MINIO_SECRET_KEY=miniosecret" \
            minio/minio server /data --console-address ":9001"
          sleep 10

      - name: Create test environment file
        run: |
          cp .env .env.test
          sed -i 's/^API_ENCRYPTION_KEY=.*/API_ENCRYPTION_KEY=test_encryption_key/' .env.test
          sed -i 's/^JWT_SECRET=.*/JWT_SECRET=test_jwt_secret/' .env.test
          sed -i 's/^MINIO_ACCESS_KEY=.*/MINIO_ACCESS_KEY=minio/' .env.test
          sed -i 's/^MINIO_SECRET_KEY=.*/MINIO_SECRET_KEY=miniosecret/' .env.test
          sed -i 's/^REDIS_PASSWORD=.*/REDIS_PASSWORD=testpassword/' .env.test
          sed -i 's/^INTERNAL_API_KEY=.*/INTERNAL_API_KEY=test_internal_key/' .env.test
          sed -i 's/^COUCH_DB_PASSWORD=.*/COUCH_DB_PASSWORD=test_couchdb_pass/' .env.test
          echo "TEST_MODE=true" >> .env.test

      - name: Launch Budibase stack
        run: |
          docker-compose -f docker-compose.yaml --env-file .env.test up -d
          sleep 30

      - name: Verify health endpoint
        run: |
          curl -s http://localhost:10000/api/health | grep "OK" || exit 1

      - name: Clean up resources
        if: always()
        run: |
          docker-compose -f docker-compose.yaml down
          docker stop minio
          docker rm minio
