name: Budibase CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Non-secret environment variables
  APP_PORT: 4002
  WORKER_PORT: 4003
  MINIO_PORT: 4004
  COUCH_DB_PORT: 4005
  REDIS_PORT: 6379
  WATCHTOWER_PORT: 6161
  BUDIBASE_ENVIRONMENT: DEVELOPMENT

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate configuration files
        run: |
          # Check for docker-compose.yaml (note the .yaml extension)
          if [ ! -f docker-compose.yaml ]; then
            echo "Error: docker-compose.yaml file is missing"
            exit 1
          fi
          
          # Check for .env (for CI/CD safety)
          if [ ! -f .env ]; then
            echo "Error: .env file is missing - create one based on your .env but with placeholder values"
            exit 1
          fi

  test:
    needs: validate
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
      
      minio:
        image: minio/minio
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: miniosecret
        ports:
          - 9000:9000
        options: >-
          server /data
          --console-address ":9001"

    steps:
      - uses: actions/checkout@v4
      
      - name: Create test environment file
        run: |
          # Create .env.test from .env but with test values
          cp .env .env.test
          sed -i 's/^API_ENCRYPTION_KEY=.*/API_ENCRYPTION_KEY=test_encryption_key/' .env.test
          sed -i 's/^JWT_SECRET=.*/JWT_SECRET=test_jwt_secret/' .env.test
          sed -i 's/^MINIO_ACCESS_KEY=.*/MINIO_ACCESS_KEY=minio/' .env.test
          sed -i 's/^MINIO_SECRET_KEY=.*/MINIO_SECRET_KEY=miniosecret/' .env.test
          sed -i 's/^REDIS_PASSWORD=.*/REDIS_PASSWORD=testpassword/' .env.test
          sed -i 's/^INTERNAL_API_KEY=.*/INTERNAL_API_KEY=test_internal_key/' .env.test
          sed -i 's/^COUCH_DB_PASSWORD=.*/COUCH_DB_PASSWORD=test_couchdb_pass/' .env.test
          echo "TEST_MODE=true" >> .env.test

      - name: Launch Budibase stack
        run: |
          docker-compose -f docker-compose.yaml --env-file .env.test up -d
          sleep 30  # Wait for services to initialize

      - name: Verify health endpoint
        run: |
          curl -s http://localhost:$MAIN_PORT/api/health | grep "OK" || exit 1

      - name: Clean up resources
        if: always()
        run: |
          docker-compose -f docker-compose.yaml down
