name: Budibase CI/CD Pipeline (Dev Testing)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_PORT: 4002
  WORKER_PORT: 4003
  MINIO_PORT: 4004
  COUCH_DB_PORT: 4005
  REDIS_PORT: 6379
  MAIN_PORT: 10000
  TEST_MODE: "minimal"  # "full" for complete tests

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        cat <<EOF > .env.test
        COUCHDB_USER=admin
        COUCHDB_PASSWORD=password
        COUCHDB_SECRET=secret
        COUCHDB_CLUSTER_SIZE=1
        BB_ADMIN_USER_EMAIL=admin@example.com
        BB_ADMIN_USER_PASSWORD=admin123
        PLUGINS_DIR=/plugins
        MINIO_ROOT_USER=minio
        MINIO_ROOT_PASSWORD=miniosecret
        BUDIBASE_ENVIRONMENT=DEVELOPMENT
        EOF

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start MinIO
      run: |
        docker run -d \
          --name minio \
          -p 9000:9000 \
          -p 9001:9001 \
          -e "MINIO_ROOT_USER=minio" \
          -e "MINIO_ROOT_PASSWORD=miniosecret" \
          minio/minio server /data --console-address ":9001"
        sleep 5

    - name: Run Tests (Full Mode)
      if: env.TEST_MODE == 'full'
      run: |
        # Export variables for Docker Compose
        export COUCHDB_USER=admin
        export COUCHDB_PASSWORD=password
        
        docker-compose -f docker-compose.yaml --env-file .env.test up -d
        
        # Wait for CouchDB with credentials
        echo "Waiting for CouchDB initialization..."
        timeout 180 bash -c 'until curl -s http://admin:password@localhost:$COUCH_DB_PORT >/dev/null; do
          docker-compose logs couchdb --tail=5
          sleep 10
        done'
        
        # Create system databases with retries
        for db in _users _replicator; do
          echo "Creating $db database..."
          curl -X PUT http://admin:password@localhost:$COUCH_DB_PORT/$db || \
          (echo "Database creation failed"; docker-compose logs couchdb; exit 1)
        done
        
        # Verify services
        curl -s http://localhost:$MAIN_PORT/api/health | grep -q "OK" || \
        (docker-compose logs; exit 1)
        echo "Full test completed successfully"

    - name: Run Tests (Minimal Mode)
      if: env.TEST_MODE == 'minimal'
      run: |
        # Skip initialization checks
        docker-compose -f docker-compose.yaml --env-file .env.test up -d
        
        # Basic port checks with service names
        echo "Verifying services:"
        for port in $MAIN_PORT $APP_PORT $WORKER_PORT; do
          timeout 30 bash -c 'until nc -z localhost '$port'; do sleep 2; done' && \
          echo "Port $port responsive" || \
          (docker-compose ps; exit 1)
        done
        echo "Minimal test completed - core services running"

    - name: Cleanup
      if: always()
      run: |
        docker-compose -f docker-compose.yaml down -v --remove-orphans
        docker stop minio || true
        docker rm minio || true
        echo "Cleanup completed"
