name: Budibase Development CI/CD

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate configuration
        run: |
          # Check critical files exist
          [ -f docker-compose.yml ] || { echo "Missing docker-compose.yml"; exit 1; }
          [ -f .env.example ] || { echo "Missing .env.example"; exit 1; }
          
          # Verify placeholder values in .env.example
          grep "CHANGEME" .env.example || { 
            echo "Warning: No placeholder values found in .env.example";
          }

  test:
    needs: validate
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports: [6379:6379]
      minio:
        image: minio/minio
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: miniosecret
        ports: [9000:9000]
        command: server /data

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup test environment
        run: |
          cp .env.example .env.test
          sed -i 's/CHANGEME/minio/g' .env.test
          sed -i 's/your_redis_password/budibase/g' .env.test
          echo "TEST_MODE=true" >> .env.test

      - name: Run Budibase stack
        run: |
          docker-compose --env-file .env.test up -d
          sleep 30  # Wait for services to initialize
          
      - name: Verify health
        run: |
          curl -s http://localhost:10000/api/health | grep "OK" || exit 1
          
      - name: Capture screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: budibase-screenshots
          path: |
            screenshots/
            
      - name: Tear down
        run: docker-compose down
