name: Budibase CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_PORT: 4002
  WORKER_PORT: 4003
  MINIO_PORT: 4004
  COUCH_DB_PORT: 4005
  REDIS_PORT: 6379
  WATCHTOWER_PORT: 6161
  BUDIBASE_ENVIRONMENT: DEVELOPMENT
  MAIN_PORT: 10000

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate configuration
        run: |
          [ -f docker-compose.yaml ] || { echo "Missing docker-compose.yaml"; exit 1; }
          [ -f .env ] || { echo "Missing .env file"; exit 1; }

  test:
    needs: validate
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up MinIO
        run: |
          docker run -d \
            --name minio \
            -p 9000:9000 \
            -p 9001:9001 \
            -e "MINIO_ROOT_USER=minio" \
            -e "MINIO_ROOT_PASSWORD=miniosecret" \
            minio/minio server /data --console-address ":9001"
          sleep 10

      - name: Create test environment
        run: |
          cp .env .env.test
          echo "TEST_MODE=true" >> .env.test
          echo "MINIO_ROOT_USER=minio" >> .env.test
          echo "MINIO_ROOT_PASSWORD=miniosecret" >> .env.test

      - name: Launch Budibase stack
        run: |
          docker-compose -f docker-compose.yaml --env-file .env.test up -d
          echo "Waiting for services to initialize..."
          sleep 45

      - name: Debug services
        run: |
          docker ps -a
          docker-compose -f docker-compose.yaml logs
          curl -v http://localhost:10000 || true
          docker inspect bbproxy | grep -A 10 "Ports"

      - name: Verify health endpoint
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:$MAIN_PORT/api/health | grep -q "OK"; then
              echo "Health check passed"
              exit 0
            fi
            echo "Attempt $i/10: Health check failed, retrying in 10 seconds..."
            sleep 10
          done
          echo "Health check failed after 10 attempts"
          exit 1

      - name: Clean up
        if: always()
        run: |
          docker-compose -f docker-compose.yaml down
          docker stop minio || true
          docker rm minio || true
