name: Budibase CI/CD Pipeline (Dev Testing)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  APP_PORT: 4002
  WORKER_PORT: 4003
  MINIO_PORT: 4004
  COUCH_DB_PORT: 4005
  REDIS_PORT: 6379
  MAIN_PORT: 10000
  TEST_MODE: "minimal"  # Change to "minimal" for quick tests

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        # Create .env.test with all required variables
        cat <<EOF > .env.test
        COUCHDB_USER=admin
        COUCHDB_PASSWORD=password
        BB_ADMIN_USER_EMAIL=admin@example.com
        BB_ADMIN_USER_PASSWORD=admin123
        PLUGINS_DIR=/plugins
        MINIO_ROOT_USER=minio
        MINIO_ROOT_PASSWORD=miniosecret
        EOF

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start MinIO
      run: |
        docker run -d \
          --name minio \
          -p 9000:9000 \
          -p 9001:9001 \
          -e "MINIO_ROOT_USER=minio" \
          -e "MINIO_ROOT_PASSWORD=miniosecret" \
          minio/minio server /data --console-address ":9001"
        sleep 5

    - name: Run Tests (Full Mode)
      if: env.TEST_MODE == 'full'
      run: |
        # Start services with proper initialization
        docker-compose -f docker-compose.yaml --env-file .env.test up -d
        
        # Wait for CouchDB
        timeout 120 bash -c 'until curl -s http://admin:password@localhost:$COUCH_DB_PORT >/dev/null; do
          echo "Waiting for CouchDB..."
          sleep 5
        done'
        
        # Create system databases
        curl -X PUT http://admin:password@localhost:$COUCH_DB_PORT/_users
        curl -X PUT http://admin:password@localhost:$COUCH_DB_PORT/_replicator
        
        # Verify services
        curl -s http://localhost:$MAIN_PORT/api/health | grep -q "OK" || exit 1
        echo "Full test completed successfully"

    - name: Run Tests (Minimal Mode)
      if: env.TEST_MODE == 'minimal'
      run: |
        # Start services without thorough checks
        docker-compose -f docker-compose.yaml --env-file .env.test up -d
        
        # Just check if ports are open
        timeout 30 bash -c 'until nc -z localhost $MAIN_PORT; do sleep 1; done'
        echo "Minimal test completed - services are up"

    - name: Cleanup
      if: always()
      run: |
        docker-compose -f docker-compose.yaml down -v
        docker stop minio || true
        docker rm minio || true
