name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # [Your existing CI steps...]

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Write private key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/lowcode.pem
          chmod 600 ~/.ssh/lowcode.pem

      - name: Install Docker and Budibase on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lowcode.pem ubuntu@ec2-54-74-97-194.eu-west-1.compute.amazonaws.com << 'EOF'
          # Install Docker
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ubuntu

          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Create directory for Budibase
          mkdir -p ~/budibase
          EOF

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/lowcode.pem docker-compose.yaml ubuntu@ec2-54-74-97-194.eu-west-1.compute.amazonaws.com:~/budibase/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/lowcode.pem .env ubuntu@ec2-54-74-97-194.eu-west-1.compute.amazonaws.com:~/budibase/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/lowcode.pem your-app.tar.gz ubuntu@ec2-54-74-97-194.eu-west-1.compute.amazonaws.com:~/budibase/

      - name: Start Budibase and import app
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lowcode.pem ubuntu@ec2-54-74-97-194.eu-west-1.compute.amazonaws.com << 'EOF'
          cd ~/budibase
          docker-compose up -d

          # Wait for Budibase to start
          sleep 30

          # Import the app
          docker exec budibase cli apps --import your-app.tar.gz
          EOF

      - name: Get Public URL
        run: |
          echo "Budibase should now be running at:"
          echo "http://ec2-54-74-97-194.eu-west-1.compute.amazonaws.com:10000"
